$(document).ready(function(){
    $("#user-icon").click(function(){
        $("#check-with").toggle();
    });
    $("#place-icon").click(function(){
        $("#check-place").toggle();
    });
    $("#tagged-p").click(function(){
        $("#check-with").toggle();
    });
});
