$(document).ready(function(){
    $("#user-icon").click(function(){
    	console.log("click");
        $("#check-with").toggle();
    });
    $("#place-icon").click(function(){
        $("#check-place").toggle();
    });
});